# Generated by Django 4.2.29 on 2026-07-14 16:56

import core.fields
import core.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hordak', '0055_alter_leg_credit_alter_leg_currency_alter_leg_debit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPeriod',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='AccountPeriodID', primary_key=True, serialize=False)),
                ('start_date', core.fields.DateField(blank=True, db_column='StartDate', null=True)),
                ('end_date', core.fields.DateField(blank=True, db_column='EndDate', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True, unique=True)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=50, null=True, unique=True)),
                ('status', models.SmallIntegerField(blank=True, db_column='Status', null=True)),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AuditCreateUser', null=True)),
                ('audit_user_id_closed', models.IntegerField(blank=True, db_column='AuditCloseUser', null=True)),
            ],
            options={
                'db_table': 'tblAccountPeriod',
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='SequenceID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True, unique=True)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=50, null=True, unique=True)),
                ('prefix', models.CharField(blank=True, db_column='Prefix', max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, db_column='Suffix', max_length=50, null=True)),
                ('padding', models.SmallIntegerField(blank=True, db_column='Padding', null=True)),
            ],
            options={
                'db_table': 'tblSequence',
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AccountJournal',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='AccountJournalID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True, unique=True)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=50, null=True, unique=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('default_credit_account_id', models.ForeignKey(db_column='DefaultCreditAccountId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='defaultcreditaccounts', to='hordak.account')),
                ('default_debit_account_id', models.ForeignKey(db_column='DefaultDebitAccountId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='defaultdebitaccounts', to='hordak.account')),
                ('sequence_id', models.ForeignKey(db_column='SequenceID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sequencies', to='ledger.sequence')),
            ],
            options={
                'db_table': 'tblAccountJournal',
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
    ]
