# Generated by Django 4.2.29 on 2026-07-27 11:56

import core.fields
import core.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hordak', '0055_alter_leg_credit_alter_leg_currency_alter_leg_debit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='AccountingPeriodID', primary_key=True, serialize=False)),
                ('start_date', core.fields.DateField(blank=True, db_column='StartDate', null=True)),
                ('end_date', core.fields.DateField(blank=True, db_column='EndDate', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True, unique=True)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=50, null=True, unique=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Open'), (2, 'Locked'), (3, 'Closed')], db_column='Status', default=1)),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AuditCreateUser', null=True)),
                ('audit_user_id_closed', models.IntegerField(blank=True, db_column='AuditCloseUser', null=True)),
                ('locked_at', models.DateTimeField(blank=True, db_column='LockedAt', null=True)),
                ('closed_at', models.DateTimeField(blank=True, db_column='ClosedAt', null=True)),
                ('closed_by', models.IntegerField(blank=True, db_column='ClosedBy', null=True)),
                ('closing_transaction', models.ForeignKey(blank=True, db_column='ClosingTransactionID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='closed_account_periods', to='hordak.transaction')),
            ],
            options={
                'db_table': 'tblAccountingPeriod',
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AnalyticAxis',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='AnalyticAxisID', primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('party', 'Party'), ('funder', 'Funder')], db_column='Code', max_length=50, unique=True)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'tblAnalyticAxis',
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AnalyticValue',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='AnalyticValueID', primary_key=True, serialize=False)),
                ('party_type', models.CharField(blank=True, choices=[('insuree_family', 'Insuree/Family'), ('health_facility', 'Health Facility'), ('payment_point_manager', 'Payment Point Manager')], db_column='PartyType', max_length=50, null=True)),
                ('funder_code', models.CharField(blank=True, db_column='FunderCode', max_length=100, null=True)),
                ('external_reference', models.CharField(db_column='ExternalReference', max_length=255)),
                ('display_name', models.CharField(db_column='DisplayName', max_length=255)),
                ('axis', models.ForeignKey(db_column='AnalyticAxisID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='values', to='ledger.analyticaxis')),
            ],
            options={
                'db_table': 'tblAnalyticValue',
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='SequenceID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True, unique=True)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=50, null=True, unique=True)),
                ('prefix', models.CharField(blank=True, db_column='Prefix', max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, db_column='Suffix', max_length=50, null=True)),
                ('padding', models.SmallIntegerField(blank=True, db_column='Padding', null=True)),
            ],
            options={
                'db_table': 'tblSequence',
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LegTag',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='LegTagID', primary_key=True, serialize=False)),
                ('analytic_value', models.ForeignKey(db_column='AnalyticValueID', on_delete=django.db.models.deletion.CASCADE, related_name='leg_tags', to='ledger.analyticvalue')),
                ('leg', models.ForeignKey(db_column='LegID', on_delete=django.db.models.deletion.CASCADE, related_name='analytic_tags', to='hordak.leg')),
            ],
            options={
                'db_table': 'tblLegTag',
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LedgerJournal',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='LedgerJournalID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True, unique=True)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=50, null=True, unique=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('default_credit_account_id', models.ForeignKey(db_column='DefaultCreditAccountId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='defaultcreditaccounts', to='hordak.account')),
                ('default_debit_account_id', models.ForeignKey(db_column='DefaultDebitAccountId', on_delete=django.db.models.deletion.DO_NOTHING, related_name='defaultdebitaccounts', to='hordak.account')),
                ('sequence_id', models.ForeignKey(db_column='SequenceID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sequencies', to='ledger.sequence')),
            ],
            options={
                'db_table': 'tblLedgerJournal',
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LedgerEntryMeta',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='LedgerEntryMetaID', primary_key=True, serialize=False)),
                ('source_event_type', models.CharField(choices=[('claim_payment', 'Claim Payment'), ('invoice', 'Invoice'), ('payroll_disbursement', 'Payroll'), ('payment_point_reconciliation', 'Payment Point'), ('closing_entry', 'Closing Entry'), ('correction', 'Correction')], db_column='SourceEventType', max_length=50)),
                ('source_event_reference', models.CharField(db_column='SourceEventReference', max_length=255)),
                ('posted_at', models.DateTimeField(auto_now_add=True, db_column='PostedAt')),
                ('accounting_period', models.ForeignKey(db_column='AccountingPeriodID', on_delete=django.db.models.deletion.DO_NOTHING, to='ledger.accountingperiod')),
                ('journal', models.ForeignKey(db_column='LedgerJournalID', on_delete=django.db.models.deletion.DO_NOTHING, to='ledger.ledgerjournal')),
                ('transaction', models.OneToOneField(db_column='TransactionID', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_meta', to='hordak.transaction')),
            ],
            options={
                'db_table': 'tblLedgerEntryMeta',
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeploymentConfiguration',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='DeploymentConfigurationID', primary_key=True, serialize=False)),
                ('operating_mode', models.CharField(choices=[('local_only', 'Local Only'), ('replicated', 'Replicated')], db_column='OperatingMode', default='local_only', max_length=30)),
                ('external_system', models.CharField(blank=True, choices=[('odoo', 'Odoo'), ('sage', 'Sage')], db_column='ExternalSystem', max_length=30, null=True)),
                ('currency_code', models.CharField(db_column='CurrencyCode', max_length=10)),
                ('retained_earnings_account', models.ForeignKey(db_column='RetainedEarningsAccountID', on_delete=django.db.models.deletion.DO_NOTHING, to='hordak.account')),
            ],
            options={
                'db_table': 'tblDeploymentConfiguration',
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
    ]
